tabs:
  fields:
  
    # INCLUDE

    include_head:
        label: Head
        comment: Вставляет код в head секцию страницы
        default:
        size: large
        span: full
        type: textarea
        tab: Includes
        translatable: true
    include_body_begin:
        label: Body begin
        comment: Вставляет код в тело страницы сразу после <body>
        default:
        size: large
        span: full
        type: textarea
        tab: Includes
    include_body_end:
        label: Body end
        comment: Вставляет код в тело страницы перед </body>
        default:
        size: large
        span: full
        type: textarea
        tab: Includes
    robots:
        label: Robots.txt
        comment: "Доступны переменные: {{ url }} - адрес сайта, {{ backendUrl }} - админка"
        default:
        size: large
        span: full
        type: textarea
        tab: Includes

    block_section:
        tab: Внешний вид
        type: section
        label: Управление блоками сайта

    header_logo:
        tab: Внешний вид
        label: Логотип в шапке сайта
        type: mediafinder

    footer_logo:
        tab: Внешний вид
        label: Логотип в подвале сайта
        type: mediafinder

    footer_text:
        tab: Внешний вид
        label: Текст в подвале сайта
        type: richeditor

    color_section: 
        tab: Внешний вид
        type: section
        label: Управление палитрой сайта

    colors:
        tab: Внешний вид
        type: nestedform
        showPanel: true
        form: ~/themes/paseca/themeColors.yaml